import { Anthropic } from '@anthropic-ai/sdk';
import { NextResponse } from 'next/server';

// ─── Constants ───────────────────────────────────────────────────────────────
const MODEL = 'claude-sonnet-4-6';
const MAX_INPUT_CHARS = 15_000; // ~3,750 tokens — production safety cap
const DETECT_MAX_TOKENS = 2_000;
const HUMANIZE_MAX_TOKENS = 8_000;

// ─── Client (singleton) ──────────────────────────────────────────────────────
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || '',
});

// ─── Types ───────────────────────────────────────────────────────────────────
interface DetectResult {
  aiProbability: number;
  analysis: string;
  detectedPatterns: string[];
  sentences: { text: string; risk: 'high' | 'medium' | 'low' }[];
}

// ─── Route Handler ───────────────────────────────────────────────────────────
export async function POST(req: Request) {
  // 1. Auth guard
  if (!process.env.ANTHROPIC_API_KEY) {
    return NextResponse.json(
      { error: 'Server configuration error: API key not set.' },
      { status: 500 }
    );
  }

  // 2. Parse body
  let body: { text?: string; action?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 });
  }

  const { text, action } = body;

  // 3. Input validation
  if (!text || typeof text !== 'string' || text.trim().length === 0) {
    return NextResponse.json({ error: 'text is required and must be a non-empty string.' }, { status: 400 });
  }
  if (!action || !['detect', 'humanize'].includes(action)) {
    return NextResponse.json({ error: 'action must be "detect" or "humanize".' }, { status: 400 });
  }
  if (text.length > MAX_INPUT_CHARS) {
    return NextResponse.json(
      { error: `Text exceeds maximum length of ${MAX_INPUT_CHARS} characters.` },
      { status: 413 }
    );
  }

  const trimmedText = text.trim();

  try {
    if (action === 'detect') {
      return await handleDetect(trimmedText);
    } else {
      return await handleHumanize(trimmedText);
    }
  } catch (error: any) {
    console.error('[API Error]', error?.message ?? error);

    // Surface a friendly Anthropic API error
    const status = error?.status ?? 500;
    const message =
      error?.error?.error?.message ??
      error?.message ??
      'An unexpected error occurred.';

    return NextResponse.json({ error: message }, { status });
  }
}

// ─── Detection Handler ───────────────────────────────────────────────────────
async function handleDetect(text: string) {
  const systemPrompt = `You are an elite AI forensics analyst. Your task is to analyze text and determine whether it was written by a human or generated by an AI (ChatGPT, Claude, Gemini, etc.).

You evaluate:
1. **Perplexity** — Is the word choice predictable or surprisingly varied?
2. **Burstiness** — Does sentence length vary widely (human) or stay uniform (AI)?
3. **Hedging Language** — AI overuses phrases like "it's worth noting", "delve", "it is important to", "moreover", "furthermore", "in conclusion".
4. **Passive voice overuse** — AI tends to construct passive, impersonal sentences.
5. **Semantic coherence** — Is there a genuine personal perspective, or is it generically helpful?
6. **Transition patterns** — AI uses formulaic transitions; humans are more abrupt.

Always respond with ONLY a valid JSON object — no markdown, no code fences.`;

  const userPrompt = `Analyze this text for AI patterns and return a JSON object with exactly these keys:
- "aiProbability": integer 0–100 (0 = definitely human, 100 = definitely AI)
- "analysis": a 2–4 sentence explanation of your reasoning
- "detectedPatterns": an array of strings naming specific AI patterns found (e.g. ["excessive hedging", "uniform sentence length", "overuse of 'moreover'"]). Empty array if none.
- "sentences": an array of objects, one per sentence (max 10 sentences), each with:
  - "text": the sentence text (truncated to 80 chars)
  - "risk": "high" | "medium" | "low"  (likelihood that specific sentence is AI-generated)

Text to analyze:
"""
${text}
"""`;

  const msg = await anthropic.messages.create({
    model: MODEL,
    max_tokens: DETECT_MAX_TOKENS,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const responseText = (msg.content.find(b => b.type === 'text') as any)?.text ?? '';

  try {
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    const result: DetectResult = JSON.parse(jsonMatch ? jsonMatch[0] : responseText);

    // Normalise: clamp probability to 0–100
    result.aiProbability = Math.max(0, Math.min(100, Math.round(result.aiProbability)));

    return NextResponse.json(result);
  } catch (parseErr) {
    console.error('[Detect] JSON parse failed:', responseText);
    return NextResponse.json({ error: 'Failed to parse AI detection result.' }, { status: 500 });
  }
}

// ─── Ghost Mode Humanizer Handler ────────────────────────────────────────────
//
// "Ghost Mode" is a 2-pass pipeline:
//   Pass 1 (Adaptive Thinking) — Claude silently reasons about the AI fingerprints
//                                in the text and devises a rewrite strategy.
//   Pass 2 (Final Rewrite)     — Claude executes a surgical rewrite using those insights.
//
// This mimics how a professional human editor would first read critically,
// then rewrite — dramatically outperforming naive single-shot rewrites.
//
async function handleHumanize(text: string) {
  // ── Pass 1: Adaptive Thinking (Ghost Analysis) ──────────────────────────
  const analysisSystem = `You are an expert AI text forensics specialist and human writing coach.
Your job is to carefully identify every AI fingerprint in a piece of text, then devise a precise, targeted rewriting strategy that will make the text completely undetectable by AI detectors (GPTZero, Turnitin, Originality.ai, Copyleaks).

You must identify:
- Specific predictable word choices to replace
- Sentences with unnaturally uniform lengths to vary
- AI clichés to eliminate ("delve", "it is worth noting", "in conclusion", "furthermore", "seamlessly", "moreover", etc.)
- Passive constructions to make active
- Generic statements to make specific and vivid
- Missing personality, emotion, and quirk to inject`;

  const analysisPrompt = `Analyze this text for every AI fingerprint. Then produce a detailed rewriting strategy.

Text:
"""
${text}
"""

Output a JSON object with:
- "fingerprints": array of strings (specific AI patterns found)
- "strategy": array of strings (specific actions to take in rewrite, e.g. "Replace sentence 2 with a short punchy version", "Remove 'furthermore' from paragraph 1", "Add a rhetorical question to increase burstiness")
- "toneTarget": string describing the human voice to achieve (e.g. "confident professional", "casual student", "enthusiastic blogger")`;

  const analysisMsg = await anthropic.messages.create({
    model: MODEL,
    max_tokens: HUMANIZE_MAX_TOKENS,
    thinking: { type: 'adaptive' }, // Ghost Mode: deep silent reasoning
    system: analysisSystem,
    messages: [{ role: 'user', content: analysisPrompt }],
  });

  // Extract thinking summary and the strategy JSON
  let strategy = '';
  let thinkingSummary = '';
  for (const block of analysisMsg.content) {
    if (block.type === 'thinking') {
      thinkingSummary = (block as any).thinking ?? '';
    } else if (block.type === 'text') {
      strategy = (block as any).text ?? '';
    }
  }

  // Parse the strategy (we pass it as context to pass 2)
  let parsedStrategy: { fingerprints?: string[]; strategy?: string[]; toneTarget?: string } = {};
  try {
    const jsonMatch = strategy.match(/\{[\s\S]*\}/);
    parsedStrategy = JSON.parse(jsonMatch ? jsonMatch[0] : strategy);
  } catch {
    // Strategy parse failed — continue with pass 2 using raw strategy text
    parsedStrategy = { toneTarget: 'natural human writer' };
  }

  // ── Pass 2: Precision Ghost Rewrite ─────────────────────────────────────
  const rewriteSystem = `You are an elite human ghostwriter with 20 years of experience.
You have been given a forensic analysis of AI-generated text and a rewriting strategy.
Your job is to execute a surgical rewrite that:

MUST DO:
✓ Vary sentence lengths dramatically (mix 3-word punches with 30-word flowing sentences)  
✓ Use contractions naturally (don't, it's, you're, we've)
✓ Add one specific, concrete detail or example that only a human would think of
✓ Use active voice throughout
✓ Include at least one rhetorical question or conversational aside
✓ Use "you" or "I" to create direct human connection where appropriate
✓ Start some sentences with conjunctions (And, But, So, Yet)
✓ Use em-dashes — like this — for emphasis instead of formal parentheses

MUST NOT:
✗ Use "delve", "seamlessly", "crucial", "leverage" as a verb, "holistic", "moreover", "furthermore", "in conclusion", "it is worth noting", "it is important to", "it goes without saying"
✗ Use formulaic 5-paragraph structure
✗ End every sentence with similar length
✗ Use passive voice ("it was found that", "it can be seen that")
✗ Be generic — every sentence must feel specific and intentional

Output ONLY the rewritten text. No preamble, no commentary, no quotes around the output.`;

  const rewritePrompt = `Rewriting strategy from forensic analysis:
Fingerprints found: ${JSON.stringify(parsedStrategy.fingerprints ?? [])}
Actions to apply: ${JSON.stringify(parsedStrategy.strategy ?? [])}
Target tone: ${parsedStrategy.toneTarget ?? 'natural human writer'}

Now rewrite this original text using the strategy above:
"""
${text}
"""

Return ONLY the final rewritten text.`;

  const rewriteMsg = await anthropic.messages.create({
    model: MODEL,
    max_tokens: HUMANIZE_MAX_TOKENS,
    system: rewriteSystem,
    messages: [{ role: 'user', content: rewritePrompt }],
  });

  const humanizedText =
    (rewriteMsg.content.find(b => b.type === 'text') as any)?.text?.trim() ?? '';

  if (!humanizedText) {
    return NextResponse.json({ error: 'Humanization produced no output.' }, { status: 500 });
  }

  return NextResponse.json({
    humanizedText,
    meta: {
      fingerprintsFound: parsedStrategy.fingerprints?.length ?? 0,
      toneTarget: parsedStrategy.toneTarget ?? 'natural human writer',
      inputLength: text.length,
      outputLength: humanizedText.length,
    },
  });
}
