import { Anthropic } from '@anthropic-ai/sdk';
import { NextResponse } from 'next/server';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || '', // We check if it exists below
});

export async function POST(req: Request) {
  try {
    const { text, action } = await req.json();

    if (!text || !action) {
      return NextResponse.json({ error: 'Text and action are required' }, { status: 400 });
    }

    if (!process.env.ANTHROPIC_API_KEY) {
      return NextResponse.json({ error: 'ANTHROPIC_API_KEY is not configured in the environment variables.' }, { status: 500 });
    }

    if (action === 'detect') {
      const prompt = `Analyze the following text and determine the probability that it was generated by an AI. Provide your response as a JSON object with exactly two keys: "aiProbability" (a number between 0 and 100) and "analysis" (a brief paragraph explaining your reasoning). Do not output anything other than the JSON object.

Text to analyze:
"""
${text}
"""`;

      const msg = await anthropic.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1000,
        temperature: 0,
        system: "You are an expert AI detection system. You analyze text for patterns typical of LLMs like uniform sentence structure, lack of burstiness, common AI phrasing, and predictable vocabulary. Always respond with valid JSON.",
        messages: [{ role: 'user', content: prompt }],
      });

      // @ts-ignore
      const responseText = msg.content[0].text;
      
      try {
        const jsonMatch = responseText.match(/\{[\s\S]*\}/);
        const result = JSON.parse(jsonMatch ? jsonMatch[0] : responseText);
        return NextResponse.json(result);
      } catch (e) {
        console.error("Failed to parse JSON:", responseText);
        return NextResponse.json({ error: 'Failed to process AI response' }, { status: 500 });
      }

    } else if (action === 'humanize') {
      const prompt = `Rewrite the following text so that it sounds completely human and bypasses AI detectors. Use varied sentence structures, natural phrasing, conversational elements where appropriate, and introduce "burstiness" (a mix of short and long sentences). Ensure the core message and meaning remain the same, but the tone should be natural and authentically human. 

Return ONLY the rewritten text, without any introductory or concluding remarks.

Text to humanize:
"""
${text}
"""`;

      const msg = await anthropic.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        temperature: 0.7,
        system: "You are an expert human copywriter. Your goal is to rewrite text so it reads as if a real person wrote it, completely bypassing any AI detectors. Avoid common AI clichés.",
        messages: [{ role: 'user', content: prompt }],
      });

      // @ts-ignore
      const responseText = msg.content[0].text;
      return NextResponse.json({ humanizedText: responseText.trim() });

    } else {
      return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
    }

  } catch (error: any) {
    console.error('API Error:', error);
    return NextResponse.json({ error: error.message || 'An error occurred' }, { status: 500 });
  }
}
