export const seoData: Record<string, { title: string; h1: string; description: string; metaDesc: string }> = {
  "ai-detector": {
    title: "Free AI Detector Tool",
    h1: "Advanced AI Detector",
    description: "Scan essays, articles, and content to determine if it was written by ChatGPT, Claude, or other AI models.",
    metaDesc: "Use our highly accurate AI detector to instantly check if content is human or AI-generated. Ideal for teachers, students, and publishers."
  },
  "ai-humanizer": {
    title: "Best AI Text Humanizer",
    h1: "AI Text Humanizer",
    description: "Convert robotic, AI-generated text into natural, human-like content that bypasses AI detectors effortlessly.",
    metaDesc: "Humanize AI text instantly with our advanced AI humanizer. Bypass detectors and create authentic content naturally."
  },
  "chatgpt-detector": {
    title: "ChatGPT Detector | Check AI Text",
    h1: "ChatGPT Content Detector",
    description: "Specifically tuned to identify text generated by OpenAI's ChatGPT. Ensure your content is 100% original.",
    metaDesc: "Check any text with our free ChatGPT detector. Identify AI patterns and ensure your writing is completely human."
  },
  "seo-ai-humanizer": {
    title: "SEO AI Humanizer for Bloggers",
    h1: "SEO AI Humanizer",
    description: "Optimize your AI-generated blog posts to sound human and bypass Google's AI helpful content updates.",
    metaDesc: "The best SEO AI humanizer for bloggers and marketers. Rank higher by humanizing your AI content to bypass detectors."
  },
  "ai-detector-for-students": {
    title: "AI Detector for Students & Essays",
    h1: "AI Detector for Students",
    description: "Check your essays and assignments before submission. See exactly what your teachers see when they scan your work.",
    metaDesc: "The ultimate AI detector for students. Scan your essays for AI probability and avoid plagiarism flags before turning them in."
  },
  "free-ai-humanizer": {
    title: "Free AI Humanizer Tool",
    h1: "Free AI Humanizer",
    description: "Don't pay expensive subscriptions. Use our free tool to rewrite AI text into undetectable human content.",
    metaDesc: "Looking for a free AI humanizer? Rewrite ChatGPT text to bypass AI detectors completely free."
  },
  "turnitin-ai-checker": {
    title: "Turnitin AI Checker Alternative",
    h1: "Pass the Turnitin AI Checker",
    description: "Test your content against algorithms similar to Turnitin. Detect AI and humanize it before submission.",
    metaDesc: "Use our Turnitin AI checker alternative to scan your essays. Detect and humanize AI text to ensure academic integrity."
  },
  "gptzero-alternative": {
    title: "Best GPTZero Alternative",
    h1: "GPTZero Alternative",
    description: "A more accurate, versatile alternative to GPTZero. Detect AI and humanize it all in one platform.",
    metaDesc: "Discover the best GPTZero alternative. Accurately detect AI content and seamlessly humanize it to bypass scanners."
  },
  "plagiarism-checker": {
    title: "AI Plagiarism Checker",
    h1: "AI Plagiarism Checker",
    description: "Scan documents for traditional plagiarism and AI-generated content simultaneously. Ensure complete originality.",
    metaDesc: "The ultimate AI plagiarism checker. Ensure your content is 100% original and free from both copied text and AI generation."
  }
};
