export interface SeoPageData {
  title: string;
  h1: string;
  description: string;
  metaDesc: string;
  keywords: string[];
  heroSubtitle: string;
  canonicalSlug: string;
}

export const seoData: Record<string, SeoPageData> = {
  "ai-detector": {
    title: "Free AI Detector Tool — Check Any Text Instantly",
    h1: "Free AI Content Detector",
    description: "Scan essays, articles, and content to determine if it was written by ChatGPT, Claude, Gemini, or any AI model. Instant results with sentence-level highlighting.",
    metaDesc: "Use our highly accurate free AI detector to instantly check if content is human or AI-generated. Trusted by 100K+ teachers, students & publishers. No sign-up required.",
    keywords: ["free AI detector", "AI content detector", "AI checker online", "check if text is AI", "AI detection tool"],
    heroSubtitle: "Check any text instantly. Our AI detector is powered by advanced NLP to identify ChatGPT, Claude, and Gemini-generated content with high accuracy.",
    canonicalSlug: "ai-detector",
  },
  "ai-humanizer": {
    title: "Best AI Text Humanizer — Bypass AI Detectors Instantly",
    h1: "AI Text Humanizer — Make AI Sound Human",
    description: "Transform robotic AI-generated text into natural, engaging, human-like content that bypasses all major AI detectors including Turnitin, GPTZero, and Originality.ai.",
    metaDesc: "Humanize AI text instantly with the #1 AI humanizer. Bypass Turnitin, GPTZero & Originality.ai detectors. Free, fast, and 100% undetectable output. No sign-up needed.",
    keywords: ["AI humanizer", "humanize AI text", "AI text humanizer", "best AI humanizer", "bypass AI detection"],
    heroSubtitle: "Transform AI-generated text into natural, undetectable human writing. Works with ChatGPT, Claude, Gemini, and all major AI models.",
    canonicalSlug: "ai-humanizer",
  },
  "chatgpt-detector": {
    title: "ChatGPT Detector — Detect ChatGPT Text Free",
    h1: "ChatGPT Content Detector",
    description: "Specifically tuned to identify text generated by OpenAI's ChatGPT models (GPT-3.5, GPT-4, GPT-4o). Get detailed sentence-by-sentence AI probability breakdown.",
    metaDesc: "Check any text with our free ChatGPT detector. Identify GPT-4 & GPT-4o patterns with 98% accuracy. Trusted by thousands of educators and hiring managers.",
    keywords: ["ChatGPT detector", "detect ChatGPT text", "ChatGPT content checker", "is this ChatGPT", "GPT-4 detector"],
    heroSubtitle: "The most accurate ChatGPT detector on the web. Identify GPT-4, GPT-4o, and ChatGPT-3.5 generated content with a single click.",
    canonicalSlug: "chatgpt-detector",
  },
  "seo-ai-humanizer": {
    title: "SEO AI Humanizer — Rank Higher with Human-Sounding Content",
    h1: "SEO AI Humanizer for Bloggers & Marketers",
    description: "Optimize your AI-generated blog posts and articles to pass Google's Helpful Content Update checks. Keep your target keywords while making content read naturally.",
    metaDesc: "The #1 SEO AI humanizer for bloggers and content marketers. Humanize AI content to protect your Google rankings from Helpful Content Update penalties. Free to use.",
    keywords: ["SEO AI humanizer", "humanize AI content for SEO", "AI content SEO tool", "bypass Google AI detection", "AI blog humanizer"],
    heroSubtitle: "Protect your organic rankings. Humanize AI-written blog posts to pass Google's Helpful Content Update and outrank competitors.",
    canonicalSlug: "seo-ai-humanizer",
  },
  "ai-detector-for-students": {
    title: "AI Detector for Students — Check Essays Before Submission",
    h1: "AI Detector for Students & Essays",
    description: "Check your essays and assignments before submitting to Turnitin or your teacher. See exactly what AI probability score your work will receive.",
    metaDesc: "Free AI detector for students. Scan your essay for AI probability and fix it before submission. Works just like Turnitin's AI indicator. 100% free, no sign-up.",
    keywords: ["AI detector for students", "essay AI checker", "student AI detector", "check essay for AI", "AI essay scanner"],
    heroSubtitle: "Check your essay before your teacher does. Our AI detector mirrors academic tools like Turnitin so you can identify and fix AI-flagged sections.",
    canonicalSlug: "ai-detector-for-students",
  },
  "free-ai-humanizer": {
    title: "Free AI Humanizer — No Sign-Up, Unlimited Use",
    h1: "Free AI Humanizer Tool",
    description: "Don't pay expensive subscriptions. Use our completely free AI humanizer to rewrite ChatGPT and AI text into undetectable, natural human content. No account required.",
    metaDesc: "The best free AI humanizer online. Rewrite ChatGPT text to bypass AI detectors — completely free, unlimited use, no sign-up, no watermarks.",
    keywords: ["free AI humanizer", "AI humanizer free", "free humanize AI text", "no sign up AI humanizer", "unlimited AI humanizer"],
    heroSubtitle: "The only truly free AI humanizer. Unlimited rewrites, no sign-up, no watermarks. Humanize ChatGPT text to bypass any AI detector for free.",
    canonicalSlug: "free-ai-humanizer",
  },
  "turnitin-ai-checker": {
    title: "Turnitin AI Checker — Scan Your Essay Before Submission",
    h1: "Turnitin AI Checker Alternative",
    description: "Simulate Turnitin's AI detection algorithm before submitting your essay. Identify AI-flagged sections and humanize them instantly to ensure academic integrity.",
    metaDesc: "Free Turnitin AI checker alternative. Scan your essay for AI patterns before submission. Humanize flagged sections to avoid academic penalties. Students trust it.",
    keywords: ["Turnitin AI checker", "bypass Turnitin AI detection", "Turnitin AI detector alternative", "check essay Turnitin", "pass Turnitin AI check"],
    heroSubtitle: "Simulate Turnitin's AI scanner before your submission deadline. Identify exactly which paragraphs are flagged and humanize them instantly.",
    canonicalSlug: "turnitin-ai-checker",
  },
  "gptzero-alternative": {
    title: "Best GPTZero Alternative — Free & More Accurate",
    h1: "GPTZero Alternative",
    description: "A more accurate, versatile alternative to GPTZero. Detect AI content and humanize it all within a single platform. Free to use with no word limits.",
    metaDesc: "The best free GPTZero alternative. More accurate AI detection with built-in humanizer. No word limits, no sign-up. Try the #1 GPTZero replacement now.",
    keywords: ["GPTZero alternative", "better than GPTZero", "GPTZero replacement", "free GPTZero alternative", "AI detector like GPTZero"],
    heroSubtitle: "Everything GPTZero does, plus a built-in AI humanizer — for free. Get more accurate AI detection with actionable one-click humanization.",
    canonicalSlug: "gptzero-alternative",
  },
  "plagiarism-checker": {
    title: "AI Plagiarism Checker — Detect AI & Plagiarism at Once",
    h1: "AI Plagiarism Checker",
    description: "Scan documents for traditional plagiarism AND AI-generated content simultaneously. The only tool that checks for copied text and AI authorship in one click.",
    metaDesc: "The ultimate free AI plagiarism checker. Scan for both plagiarism and AI-generated content at once. Trusted by students, teachers, and publishers worldwide.",
    keywords: ["AI plagiarism checker", "plagiarism and AI checker", "check AI and plagiarism", "free plagiarism AI detector", "AI content plagiarism tool"],
    heroSubtitle: "The world's only combined AI detection and plagiarism checker. Run a single scan to verify both originality and human authorship simultaneously.",
    canonicalSlug: "plagiarism-checker",
  },
  "bypass-copyleaks": {
    title: "Bypass Copyleaks AI Detector — Free Tool",
    h1: "Bypass Copyleaks AI Detector",
    description: "Humanize your AI-generated text to pass Copyleaks AI detection checks. Our advanced rewriting engine restructures text to evade Copyleaks' NLP algorithms.",
    metaDesc: "Bypass the Copyleaks AI detector for free. Humanize AI text so it passes Copyleaks scans. 100% effective, free to use, no sign-up required.",
    keywords: ["bypass Copyleaks", "Copyleaks AI detector bypass", "pass Copyleaks AI check", "Copyleaks humanizer", "Copyleaks AI"],
    heroSubtitle: "Make your AI text pass Copyleaks checks. Our humanizer is specifically tuned to evade Copyleaks' proprietary NLP detection patterns.",
    canonicalSlug: "bypass-copyleaks",
  },
  "ai-humanizer-for-essays": {
    title: "AI Humanizer for Essays — Pass Turnitin & Copyleaks",
    h1: "AI Humanizer for Essays",
    description: "Specifically designed for students. Humanize AI-assisted essay drafts to meet academic standards while maintaining your argument's core meaning and structure.",
    metaDesc: "The best AI humanizer for essays. Rewrite AI-drafted essays to pass Turnitin, GPTZero, and Copyleaks while preserving your thesis and arguments. Free for students.",
    keywords: ["AI humanizer for essays", "essay humanizer AI", "humanize essay AI", "student AI essay humanizer", "make essay pass AI detector"],
    heroSubtitle: "Built for students. Humanize your AI-drafted essay to pass all academic AI detectors while keeping your thesis, arguments, and structure intact.",
    canonicalSlug: "ai-humanizer-for-essays",
  },
  "humanize-chatgpt-text": {
    title: "Humanize ChatGPT Text — Make It 100% Undetectable",
    h1: "Humanize ChatGPT Text Instantly",
    description: "Convert ChatGPT's robotic output into natural, flowing human writing. Our tool specifically targets and rewrites the linguistic patterns that make ChatGPT text detectable.",
    metaDesc: "Humanize ChatGPT text instantly. Transform GPT-4 and ChatGPT output into 100% undetectable human writing. Free, fast, no limits. The best ChatGPT humanizer online.",
    keywords: ["humanize ChatGPT text", "ChatGPT text humanizer", "make ChatGPT text human", "ChatGPT to human text", "humanize GPT-4 text"],
    heroSubtitle: "The fastest way to humanize ChatGPT text. Specifically engineered to remove GPT-4 and ChatGPT-3.5 linguistic signatures in seconds.",
    canonicalSlug: "humanize-chatgpt-text",
  }
};
